server:
  port: 8081
spring:
  application:
    name: circuit-breaker-app
  data:
    mongodb:
      uri: ${MONGODB_DB_URL:mongodb://mongodb:27017/circuit-breaker?replicaSet=rs0}
      database: circuit-breaker
      auto-index-creation: true
  testcontainers:
    enabled: true
    reuse:
      enabled: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /doc

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    metrics:
      enabled: true

logging:
  level:
    ROOT: INFO
    io.github.resilience4j: DEBUG
    org.springframework.web: DEBUG

resilience4j:
  circuitbreaker:
    instances:
      createOrder:
        register-health-indicator: true
        failure-rate-threshold: 5
        slow-call-rate-threshold: 10
        slow-call-duration-threshold: 2500ms
        minimum-number-of-calls: 100
        wait-duration-in-open-state: 5000ms
        automatic-transition-from-open-to-half-open-enabled: true
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        permitted-number-of-calls-in-half-open-state: 10
      updateOrderStatus:
        register-health-indicator: true
        failure-rate-threshold: 5
        slow-call-rate-threshold: 10
        slow-call-duration-threshold: 2500ms
        minimum-number-of-calls: 100
        wait-duration-in-open-state: 5000ms
        automatic-transition-from-open-to-half-open-enabled: true
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        permitted-number-of-calls-in-half-open-state: 10
  bulkhead:
    instances:
      createOrder:
        max-concurrent-calls: 100
      updateOrderStatus:
        max-concurrent-calls: 100
  thread-pool-bulkhead:
    instances:
      createOrder:
        max-thread-pool-size: 100
        core-thread-pool-size: 80
        queue-capacity: 100
      updateOrderStatus:
        max-thread-pool-size: 100
        core-thread-pool-size: 80
        queue-capacity: 100
  timelimiter:
    instances:
      createOrder:
        timeout-duration: 1000ms
        cancel-running-future: true
      updateOrderStatus:
        timeout-duration: 1000ms
        cancel-running-future: true
